config/routes.rb
Rails.application.routes.draw do
  get "/" =>"blogs#top"

   resources :blogs

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

   

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	add_flash_types :success, :notice, :warning, :danger
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  	def top
  	end

  	def index
  		@blog = Blog.new
      @blogs = Blog.all.order(updated_at: :asc)
  	end

  	def create
      	 blog = Blog.new(blog_params)
        # DBへ保存する
      if blog.save
        flash[:success] = "Book was successfully created."
        redirect_to blog_path(blog.id)
      end
    end


  	def show
  		@blog = Blog.find(params[:id])
 	  end

  	def edit
  		@blog = Blog.find(params[:id])
  	end

  	def update
  		blog = Blog.find(params[:id])
      if blog.update(blog_params)
        flash[:notice] = "Book was successfully updated."
        redirect_to blog_path(blog)
      end

    end


 	  def destroy
        blog = Blog.find(params[:id])
        blog.destroy
        redirect_to blogs_path
    end

   private
    def blog_params
      params.require(:blog).permit(:title, :body)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/edit.html.erb
	<div class="body_edit">
		<div class="edit-top">
			<h1 class="edit-top-title"><strong>Editing Book</strong></h1>
		</div>

		<div class="edit-contents">

		<!-- form_for部分 -->
			<%= form_for(@blog) do |f| %>
  		 	 <h4 class="edit-title">Title</h4>
  		 	 <%= f.text_field :title, class: "book_title"%>

  		 	 <h4 class="edit-body">Body</h4>
  		 	 <%= f.text_area :body,class: "book_body" %>
  		 	 <br>
  		 	 <div class="update-book">
  		 	 <%= f.submit 'update book' %>
  		 	</div>
  			<% end %>

  		</div>


		<div class="edit-step">
			<div class="show-step">
			<%= link_to "Show", blog_path(@blog),class: "show_#{@blog.id}"%></div>
			<div class="show-item">|</div>
			<div class="back-step"><%=link_to "Back", blogs_path(@blog) ,class: "back"%></div>
		</div>
	</div>

app/views/blogs/index.html.erb
		<h1 class="index-top">Books</h1>


		<div class="index-item">

			<table >
				<thead>

          			<tr>
          			<th class="indextitle"><strong>Title</strong></th>
          			<th class="body"><strong>Body</strong></th>
          			<th class="contents"></th>
          			</tr>

          		</thead>

          		<tbody>


 				<% @blogs.each do |blog| %>
 					<tr class ="blogs-item">
             		<td class="blog-title"><%= blog.title%></td>

             		<td class="blog-text"><%= blog.body%></td>

             		<td class="blog-contents">
            		 <%= link_to "Show", blog_path(blog.id),class: "show_#{blog.id}"%>
           		  	<%=link_to "Edit", edit_blog_path(blog.id),class: "edit_#{blog.id}" %>
					<%= link_to 'Destroy',blog_path(blog.id), method: :delete, data: { confirm: 'Are you sure?' } ,class: "destroy_#{blog.id}"%>
					</td>
 					 </tr>

        		<% end %>
        		</tbody>

       		 </table>


			</div>
				<div class="new-book">
				<h2 class="newbook-top">New book</h2>
				<!-- form_for部分 -->
				<%= form_for(@blog) do |f| %>

 				   <h4 class="newbook-title">Title</h4>

 				   <%= f.text_field :title ,class: "book_title"%>

				    <h4 class="newbook-body">Body</h4>

				    <%= f.text_area :body ,class: "book_body"%>
				    <br>

 				   <%= f.submit 'create box' %>
				<% end %>
				</div>

		</div>

app/views/blogs/show.html.erb
		<div class="show">

				<% if flash[:success] %>
     			 <div class="flash">
      			  <%= flash[:success] %>
      			</div>
    			<% end %>


				<% if flash[:notice] %>
   			 	  <div class="flash">
   			     <%= flash[:notice] %>
   			  	 </div>
   				<% end %>



			<div class="show-contents">
				<div class="title-box">
					<div class="show-title"><strong>Title:</strong></div>
					<p class="put-title"><%= @blog.title %></p>
				</div>


				<div class="body-box">
					<div class="show-body"><strong>Body:</strong></div>
					<p class="put-body"><%= @blog.body %></p>
				</div>
			</div>


			<div class="step-contents">
				<div class="show-edit"><%= link_to "Edit", edit_blog_path(@blog),class: "edit_#{@blog.id}" %></div>
				<div class="show-item">|</div>
				<div class="show-back"><%=link_to "Back", blogs_path(@blog),class: "back"%></div>
			</div>

		</div>

app/views/blogs/top.html.erb
<div class="top-body">

	<div class="top-title">
		<strong>
		ようこそ<span class="top-span">Bookers</span>へ！
		</strong>
	</div>

	<div class ="top-text">

		<p class="top-text-item"><strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や<br></p>

		<p class="top-text-item">印象を共有し交換することができます</p>

		<a href ="/blogs" class ="top-start">start</a>
	</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kadaidesu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>